if(MSVC71)
	set(tng_compiler vc71)
	add_definitions(-DTNG_VC=71)
	add_definitions(-DTNG_VC71)
elseif(MSVC80)
	set(tng_compiler vc80)
	add_definitions(-DTNG_VC=80)
	add_definitions(-DTNG_VC80)
elseif(MSVC90)
	set(tng_compiler vc90)
	add_definitions(-DTNG_VC=90)
	add_definitions(-DTNG_VC90)
elseif(MSVC10)
	set(tng_compiler vc10)
	add_definitions(-DTNG_VC=100)
	add_definitions(-DTNG_VC10)
elseif(MSVC11)
	set(tng_compiler vc11)
	add_definitions(-DTNG_VC=110)
	add_definitions(-DTNG_VC11)
elseif(MSVC12)
	set(tng_compiler vc12)
	add_definitions(-DTNG_VC=120)
	add_definitions(-DTNG_VC12)
elseif(MSVC13)
	set(tng_compiler vc13)
	add_definitions(-DTNG_VC=130)
	add_definitions(-DTNG_VC13)
elseif(MSVC14)
	set(tng_compiler vc14)
	add_definitions(-DTNG_VC=140)
	add_definitions(-DTNG_VC14)
elseif(CMAKE_COMPILER_IS_GNUCC)
	set(tng_compiler gcc)
	add_definitions(-DTNG_GCC)
elseif(CMAKE_COMPILER_IS_GNUCXX)
	set(tng_compiler g++)
	add_definitions(-DTNG_G++)
elseif(EMCC)
	set(tng_compiler emcc)
	add_definitions(-DTNG_EMCC)
endif()